### ISSUE TITLE
Why use Julian Calendar for the transfer?

### ISSUE THREAD

**Issue by coolBreezes** [persian-calendar/DroidPersianCalendar#636]
Hello, Thank you for your sharing, I have one question to ask.
Why should the Gregorian calendar and the Persian calendar use the Julian Calendar for the transfer?
Isn't it possible to use the Gregorian calendar to transfer directly?

> متشکرم

**Comment by ebraminio** [comment]
Hey, first of all, thanks for the interest!

JDN, https://en.wikipedia.org/wiki/Julian_day is versatile, every calendar can be converted to/from it and considering the fact we have three relevant calendars in Iran/Afghanistan (Persian, Islamic/Lunar, Gregorian), that's why taking JDN as the intermediary concept between all the calendars is just make things just easier.

Have a look https://github.com/persian-calendar/calendar and @catull's https://github.com/catull/calendariale they both use JDN as the common concept between the calendars to ease conversion and so.

Btw, we would love to have Chinese calendar inside this app also! The UI is able to handle more number of calendars as I always have been thinking about adding more number of calendars and not being limited to ones are relevant to us! We even have a Japanese translation of the UI inside the app and a Chinese translation for the UI also would be cool!

Am closing the issue but feel free to continue the discussion here. Thanks :)

**Comment by coolBreezes** [comment]
Thank you for your patient answers :）
